### ISSUE TITLE
Our content types don't map directly onto DOIs datacite profile. Map ours to theirs.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1166] opened 2018-01-25 15:54 UTC
Until this is fixed I can fix them manually. Still labeled it as high.

ScholarSphere      ->    DOI
---
Article  -> Text
Audio -> Sound
Book ->
Capstone Project -> Text
Conference Proceeding -> Text
Dataset -> Dataset
Image -> Image
Journal -> Text
Map or Cartographic Material -> Image
Part of  Book -> Text
Poster -> Audiovisual
Presentation -> Audiovisual
Project -> Other
Report -> Text
Research Paper -> Text
Software or Program Code -> Software
Video -> Audiovisual
Other -> Other

**Comment by awead** [comment] 2018-01-25 16:08
Duplicate of #1167

**Closed as completed by awead** 2018-01-25 16:08 UTC
Labels: High
